name: Run Tests

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn build --all
      - run: yarn lerna bootstrap
      - run: yarn test
    env:
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}